### ISSUE TITLE
loading="lazy" messes up layout

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#137]
**Describe the bug**
I've noticed that placeholders were not loading properly, likely since the addition of `loading="lazy"`, which causes my site's grid layout to go out of alignment.

**To Reproduce**
1. Go to https://dev.get-business-online.com/plastic2go/product-category/plastic-crates/
2. Scroll down until the "Folding Vented Plastic Crate C2GP6411FV" is visible (searching is OK)
3. Compare the alignment of that row of products to the one above it
4. Compare the height of the images in each row

**Expected behavior**
All the product blocks should be sized identically, and all the image blocks in each sub-category should be sized identically

**Screenshots**
https://1drv.ms/u/s!AvYtwWI4b_-wszxyk4xPgpJtRa0j?e=JiOxfs

**Additional context**
There is a script on the page that relies on placeholders being sized identically to the final images. This was working OK since the addition of cached PNG placeholders, but no longer works, so I'm assuming it's because the placeholders are lazy loaded too.

**Comment by nosilver4u** [comment]
Yeah, the whole idea with the loading="lazy" is just to suppress unnecessary placeholders from loading, but I wondered if we would run into issues with that.  That makes sense if the script runs on page load and has trouble, since the placeholders won't all be loaded yet.

I didn't think to put in an override/bypass for that, so I'll get one added for the next release.

**Comment by nosilver4u** [comment]
define EWWWIO_DISABLE_NATIVE_LAZY to true, code checked in and will be in next release

**Comment by galbaras** [comment]
Thanks, Shane.

FYI, I've sent feedback to Google on this via Chrome. Hopefully, they'll improve their rendering and we'll all be happier.
