### ISSUE TITLE
Feature request: ability to recompress original images that are smaller than the max size

### ISSUE THREAD

**Issue by kimhornung** [nosilver4u/ewww-image-optimizer#138]
**Is your feature request related to a problem? Please describe.**
I have a couple of customers that upload JPG files that have been saved from Photoshop using quality that is much higher than needed. But they often upload images that are smaller than the max image size that I have defined in EWWW image size. 

For example, they will upload an 550Kb image that is 1200x1200 px. But our max size is 2560x1920, so the image is not optimized. Whereas an optimized image would only take up ~350Kb.

So I would love to have an option to tell the plugin to also optimize / recompress original images that are smaller than the max size. 

**Describe the solution you'd like**
I would love to the ability to allow the plugin to optimize / recompress original images that are smaller than the max size. 

For my purposes, this doesn't have to be a setting in the UI. I would be perfectly happy with an override using a define in wp-config.php or using a filter .

**Describe alternatives you've considered**
I have already looked through the code to see if there were any filters or actions, that I could hook into to make this happen. But it doesn't seem to be the case.

**Additional context**
If you wish, I would be happy to submit a PR with a possible solution.
I already made a suggested implementation in the following fork that I could submit:
https://github.com/kimhornung/ewww-image-optimizer/commit/5492e62e724286f6426b7a6f3b48211a16b8b2b9

I have tested the above code both when uploading a new image and when optimizing already uploaded images, and it seems to work. 

However, with the upcoming WP 5.3 release, it could make sense to proposed solution with code that saves the original, uncompressed image as an "original" image to preserve the full-quality image for future (re-)optimizations.

**Comment by nosilver4u** [comment]
Looking at your fork, it looks like you're just wanting EWWW IO to use the WP image editor to re-save the image at a lower quality, right?

If you use our premium compression with an API key, it would do something similar, but more of a "dynamic" quality adjustment. I'm not super excited about the idea of just re-saving every image uploaded (even based on filesize) to a static quality.

That said, I'll give it some more thought and let you know. In the meantime, you can try out the premium compression on the API by opting into the usage tracking (Contribute tab of the settings).

**Comment by kimhornung** [comment]
Yes, the focus of my fork was to simply re-save the image at lower quality because that was a relatively easy way to avoid the bandwidth problems that the clients in question currently experience. 

And I completely agree with you that this is not ideal: I'm also not a big fan of reducing the quality of the "original" versions. Because that can lead to reduced quality if the users of the plugin experiment with different quality settings and run several bulk optimize operations. 

So a more solid WP-only fix would probably be to take advantage of the 5.3 functionality for storing the original image as a separate image (and yes, I realize that there might be some hoops to jump through to store the original version of these smaller images).

And thank you for the tip about considering the premium options. Sounds like I should give that a try.

**Comment by nosilver4u** [comment]
After discussing this internally, we don't feel that re-saving an image like this fits with our mindset around image optimization, which is to give folks the best savings without sacrificing quality.
For example, right on the plugin settings, it states "All methods used by the EWWW Image Optimizer are intended to produce visually identical images."

Some plugins take a more cavalier attitude towards quality, like Resmush.it and Robin Image Optimizer (that uses the Resmush.it API), but that isn't a road we want to travel.

**Comment by kimhornung** [comment]
Thank you for considering it. 

Would you be open for only implementing such a feature for WP 5.3 and later where the original image can be stored side-by-side and thus shouldn't sacrifice quality? (and yes, I know that it's already possible using the premium options - but I thought it would be worth asking).

**Comment by nosilver4u** [comment]
That is something I'm thinking about replicating into our process. Specifically for when we DO scale images down, to keep the original image and store it the same as WP 5.3. However, last I checked, there were still some logistics being discussed within the core media team, so I won't look at that probably any earlier than WP 5.4.

Such a feature is especially useful now that core has a mechanism for generating thumbs from the original rather than the scaled "full" image. In such cases, it makes sense to me to keep that original available, since it will always be higher quality and better for generating thumbs.

Keeping the original before we do any lossy (premium) compression would be an interesting extension of that same idea, allowing regeneration of thumbs from the pre-compressed version.
However, I'm not sure I want to deviate from our current setup, where we store those backups on our API rather than on the local server (to make sure we aren't increasing the disk space/usage).

So, keeping the original for scaled images? Probably. But keeping the original, full-size version locally on disk for compressed images? Not likely.
