### ISSUE TITLE
check image dimensions to see if re-optimization is necessary

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#147]
**Describe the bug**

After setting up resize settings of 960x0 and allowing resizing of existing images, I tried these two things, and neither worked:

1. Bulk optimization - did not detect images larger than the new maximum width
2. Single-image optimization - original image dimensions did not change for some images. At first, I thought this was for sizes close to 960px, but a 1000px image resized OK, while nothing happened to a 1237px-wide one and a couple of 1024px-wide images

**Expected behavior**

Images larger than the maximum should be detected, and subsequently resized, but the bulk optimizer, and the single-image optimization should resize anything large enough.

**Sample Images**

* https://dev.get-business-online.com/ronitbaras/wp-content/uploads/2015/03/stop.jpg
* https://dev.get-business-online.com/ronitbaras/wp-content/uploads/2016/07/happy-girls.jpg
* https://dev.get-business-online.com/ronitbaras/wp-content/uploads/2010/01/boys-life.jpg

**Additional context**

Potentially relevant plugins:
* Image Regenerate & Select Crop
* Media File Renamer

**Comment by nosilver4u** [comment]
1. It should only detect images larger than the new max width if you haven't optimized the images already, or if you use the Force Re-optimize option. Were you still seeing images not detected outside of these constraints? The single-image optimization does imply a forced re-optimization, which is why it behaves a little differently.
2. That's completely normal, as scaling an image down just a small amount like that will often increase the file-size beyond that of the original, and EWWW IO will only scale an image if it actually results in a smaller file.

So long as IRSC isn't set to a JPG quality higher than 82, it shouldn't impact the EWWW IO scaling process.

**Comment by galbaras** [comment]
1. Can you please outline the steps to a successful bulk resize?

2. So it's possible that resizing a 1000px image to 960px reduces the size, but resizing a 1047px image results increases it? Does the plugin resize, then compares and decides, or is there some condition that needs to be me?

Yeah, I have the quality setting at 82, as advised by my global expert on image quality ;P

**Comment by nosilver4u** [comment]
1. For a new install, just set the dimensions, and run the bulk optimizer through to completion.
But for an install where you have already compressed images with EWWW IO and are now trying to bulk resize them: you would set the max dimensions, and then run the bulk optimizer with the Force Re-optimize option checked.
2. Yes, that is possible, although successfully scaling an image from 1000px to 960px is surprising. I wouldn't have expected that to produce a smaller image (filesize), but it can happen. The image contents themselves determine how well any given image will scale/compress.

All that said, I'm seeing where there is some confusion there. The plugin certainly could check against the resize dimensions to avoid the need for "force re-optimize" (but it doesn't currently). Right now, all it does during a scan is check to see if the image has been optimized by EWWW IO previously. If it hasn't compressed an image before OR if the file size of the image has changed from what is stored in the ewwwio_images table, that's the only time it will optimize an image without the "force" flag being set.

**Comment by galbaras** [comment]
Well, since the original images were resized to 960px, there should be no need to force anything, but when I select some images and bulk optimize them, all I get is the option to scan for unoptimized images, so maybe it's not comparing the sizes?

Also, I don't want to reoptimize all of my images, and it's not clear that the bulk optimizer will only process the selected images if I do choose to force it.

The optimizer says "2 uploaded items in the Media Library have been selected with up to 13 image files per upload. The total number of images found will be displayed before optimisation begins.", followed by a button that says "Scan for unoptimized image".

I would have expected the button to say "Optimize" or some such.

**Comment by nosilver4u** [comment]
I'm not sure what you mean by your first question, do you mean file sizes, or dimensions?
At the point you've reached there before clicking "scan for unoptimized images", no image has been checked for either case (file size/dimensions).
It will indeed only check the 2 images you selected (and their thumbs) during the scanning process.

The plugin always "pre-screens" the images when you click the scan button, to see if they have been processed by EWWW IO before or not. While it's not really much of a time-saver with only 2 images selected, it saves a lot of processing time when you're dealing with hundreds or thousands of images, so that's why we do it that way.
The scanner does not check image dimensions though, only the image filesize. If the image filesize on disk is the same as what is stored in the database, the files are not added to the queue for further processing (compression & scaling) unless you check Force Re-optimize.

**Comment by nosilver4u** [comment]
And FYI, I can't access the files you linked originally, so I haven't verified whether or not they actually ought to be resized when the max size is 960px.

**Comment by galbaras** [comment]
> Well, since the original images were resized to 960px, there should be no need to force anything, but when I select some images and bulk optimize them, all I get is the option to scan for unoptimized images, so maybe it's not comparing the sizes?

> I'm not sure what you mean by your first question, do you mean file sizes, or dimensions?

I meant "dimensions", e.g. "max width" vs. the image width.

> The scanner does not check image dimensions though, only the image filesize.

Well, that's not good, because the optimizer plugin is the one doing the filesize change by applying the maximum dimensions. I think this should happen.

I've double checked all my files in Incognito and they all load just fine for me. There's no reason why you shouldn't be able to see them, although they may all be WebP versions, so maybe add `?type=original` for the JPEG.

**Comment by nosilver4u** [comment]
I agree that intuition tells us it *should* be checking dimensions. If one changes the dimensions (or sets them for the first time), it would be logical to have the scanner check the dimensions.
As such, I'm going to mark this as an enhancement to work on in the next couple releases.

**Comment by galbaras** [comment]
Thank you.

In the meantime, if I select some images and force the bulk optimizer, they will be the only ones optimized?

**Comment by nosilver4u** [comment]
The selected images will indeed be the only ones optimized, including any thumbnails, but of course you could temporarily disable optimization of all the thumbs on the Resize tab to avoid that.

**Comment by nosilver4u** [comment]
What would you think of having this be part of the "smart re-opt" feature, rather than an "always on" sort of thing?

**Comment by galbaras** [comment]
Sounds like a plan. Just needs to be clear to users of the bulk optimiser what will happen with each option.

**Comment by nosilver4u** [comment]
Bulk optimizer will now detect images that need scaling, even if previously optimized. Decided to just do it by default rather than expect folks to check an additional box for this.
Changes just checked in.

**Comment by galbaras** [comment]
Love your work :)
