### ISSUE TITLE
Bulk optimize and resize only attachments 

### ISSUE THREAD

**Issue by whiwo** [nosilver4u/ewww-image-optimizer#167]
I have 27,000 images in my content folder. Only about 1,200 of those are actually used in my website. 

Is there a way to optimize only attached images in bulk without optimizing them one by one as opposed to being forced to optimize a bunch of images not in use? This is a colossal waste of resources, time, and money.

Otherwise, great plugin.

**Comment by nosilver4u** [comment]
If you're looking to optimize the local images, no there isn't any way of even knowing which images are actually "in use" without very complicated searches through the database.

Probably the only "middle ground" between one-by-one and all at once would be to select all the attached media from the List mode of the Media Library, and Bulk Optimize those with the Bulk Actions drop-down. I couldn't find any way to query those with stock WP, but there might be a plugin that lets you filter the "attached" media. Note, the "attached" status isn't always accurate, especially once you bring in page builders, theme headers, logos, etc.

Otherwise, what you describe is much like what our Easy IO system does. Instead of mass optimizing everything on your site, is optimizes on-demand and thus is more efficient (plus it gives you way more value): https://ewww.io/easy/

**Comment by whiwo** [comment]
I only asked because the Regenerate Thumbnails plugin actually does just that. It only seeks out attached files not every single one in the directory. Nevertheless, your suggestion is actually a good one. 

I can live with only going page by page within the media directory and selecting only the ones attached to a post. Thanks!

**Comment by nosilver4u** [comment]
That's interesting, must be a new-ish feature, I hadn't seen that option before (but it's been a while since I used RT).

**Comment by whiwo** [comment]
Nevermind, I thought going page by page in the media library and only selecting the ones to optimize would work but it does not. Once you hit apply it wants to optimize everything again. It was worth a try.

**Comment by nosilver4u** [comment]
If you use the Bulk Optimize from the Bulk Actions, that does work, and it will only optimize what has been selected.
However, you will note that it also includes all thumbnails, each of which can be disabled on the EWWW IO Resize tab.
