### ISSUE TITLE
Renamer integration: images not resized on upload

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#179]
I've reported this to the author of Media File Renamer, but just in case this is due to the latest release of EWWW IO, please look into it too.

Basically, when MFR (free or Pro) is active, thumbnails are created and all the files are optimised, including WebP versions. However, the original image is not resized and remains as oversized as when it was uploaded.

To confirm, resizing works when MFR is inactive. However, both plugins were updated recently, which may have affected integration.

**Comment by nosilver4u** [comment]
Hmm, we do have a snippet for MFR that I added to move the resize hook to wp_handle_upload_prefilter rather than wp_handle_upload. I did that in order to potentially prevent resizing of 'noresize' images when MFR is active. I'll double-check that it didn't break something, but it WAS working originally when I made the change (last month I think).

**Comment by galbaras** [comment]
It definitely isn't working for me :(

Let's be clear about the steps here. This is what I think happens when an image is added to WordPress (let's ignore thumbnail creation for this):

1. Image is uploaded

2. Image is optimized and, if the filename contains 'noresize', is also resized

3. Image title is changed - it may now contain 'noresize'

4. Image is renamed - if the title contains 'noresize', so does the new filename

Steps 3 & 4 may be repeated later.

If this is the sequence, uploaded images should be resized (or not) & optimized after upload, and MFR doesn't get involved until some manual editing takes place.

Do you disagree?

**Comment by nosilver4u** [comment]
Well, that's not quite right, but I think from your description, you aren't auto-renaming during upload, right?
In either case, it doesn't matter, because here's what happened, and it IS because MFR is active, but not because of anything MFR is/isn't doing:
1. image is uploaded
2. If MFR is active, EWWW IO hooks onto wp_handle_upload_prefilter rather than wp_handle_upload.
3. EWWW IO resizes the image.
4. If rename "on upload" is enabled, MFR renames the image based on the EXIF title.
5. EWWW IO optimizes/compresses the image.

Step #2 worked when I made the change, but in an effort to eliminate a potential security concern highlighted by CodeRisk, I restricted EWWW IO to only handling images in the ABSPATH and WP_CONTENT_DIR locations.

Both changes rolled out in the 5.3 release, but were made at least a week or two apart, and I didn't remember that an image is in the /tmp/ folder during wp_handle_upload_prefilter, rather than the /uploads/ folder for wp_handle_upload.

I'll have to give it some more thought, but I think I'm going to roll-back the change for MFR, as it potentially breaks in other ways too (related to removal of metadata).

**Comment by nosilver4u** [comment]
fix committed, will be in next release

**Comment by galbaras** [comment]
ETA?

**Comment by nosilver4u** [comment]
possibly this week, but next week at the latest
