### ISSUE TITLE
Enabling WebP background images when using PICTURE tags with minimal JS

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#180]
The new PICTURE method of delivering WebP images is stated as not supporting CSS images. So I looked around for a possible solution.

Although there isn't a CSS-only solution, all the available ones include 2 steps:

1. Detect if the browser support WebP. If so, add the class "webp" to the HTML or BODY tag

2. Add image-related styles for WebP-capable browsers with the ".webp" prefix with WebP images, while using the original image format for the existing styles

Step 1 can be very quick, depending on the method used for detection, so the performance hit is negligible. However, it still required JavaScript support.

Step 2 can be done in JS, but it's better to do it in PHP, if possible. The main challenge is to keep new styles where the existing ones are, so as to retain the overall order of the styles.

Until Step 2 is implemented, would it be possible to enable the CSS processing script even in PICTURE mode? This can be a sub-option, so that people have a choice.

References:

- https://davidwalsh.name/detect-webp
- https://stackoverflow.com/questions/5573096/detecting-webp-support

**Comment by nosilver4u** [comment]
Detecting WebP support is the easy part, we already do that in JS WebP!

I did consider letting folks use JS WebP with lazy loading to catch the background-images (with only the LL JS needed), but then you might as well just use JS WebP in the first place, as you've lost most of the benefit to <picture> WebP, since the JS WebP script is quite small and loads inline already.

At any rate, if enough folks want this, I'll definitely re-consider.

**Comment by galbaras** [comment]
Oh, wait, I totally forgot about Lazy Load, which I personally.

Does this mean that if I switch to using PICTURE, my lazy-loaded backgrounds will be .webp?

Full disclosure: this is for a site on Cloudflare, where I can see that the vast majority of images end up being served as .jpg. I have a strong suspicion that switching to PICTURE will help.

**Comment by nosilver4u** [comment]
Quite the opposite, if you switch to <picture> mode, then none of the background images will be WebP. Those only work with JS WebP + Lazy Load. Note that the only background images supported are those directly inlined on the element (li, a, div, span, & section tags). There's no way to swap the images when they are in external CSS, or even in a separate <style> block.

**Comment by galbaras** [comment]
Yeah, in email, your message was missing the tags, ha ha.

I was asking if you could enable JS WebP for background images, while serving foreground ones using picture tags. This can be an option for Picture-mode, but really, if picture tags would work on every browser, why not just make this combination the new alternative method? It won't have any limitations, and it will integrate nicely with LL.

**Comment by nosilver4u** [comment]
The main issue with making picture mode the new alt method (with JS WebP for background images), is that picture tags don't work with all themes/plugins. Even with stock WP, I had to add a tiny bit of CSS to prevent gallery blocks from breaking with picture mode.

When used with the lazy loader, JS WebP is pretty good at preserving layout. There are always exceptions of course, but at this point I think JS WebP is the safer of the two methods. At this point, I'm open to adding an option to use them together as you suggested, if there is enough interest.

**Comment by galbaras** [comment]
Hmmm... Didn't think of galleries. How does that affect the layout?

I suppose one solution would be to copy all the styles applicable to IMG tags and add them to SOURCE tags, but this requires more JS and can get messy.

If you continue to offer full JS WebP, some people can still use it if the new mode breaks their site, so they've lost nothing, while others gain.

Where can I round up some votes? Where can supporters vote?

**Comment by nosilver4u** [comment]
We don't have an official "voting  platform" or anything fancy, they can just add their +1 or comments on this issue here.
But where to round up votes, I'm not sure. A lot of folks don't check the plugin page well enough to know that feature requests are all tagged on GitHub here. Maybe I can work on making that more prominent in the future.
Besides that, if you post in the forums, you might get a little traction. I know  we had a few folks follow a link for an Imsanity feature request from the forums recently.

**Comment by galbaras** [comment]
Any solution that requires JS, even a little, might as well be all JS. I'm just going to trust you to do the best with your plugin. Feel free to use my ideas.

**Comment by nosilver4u** [comment]
That was my gut feeling from the beginning. But like I said, if we get more folks requesting to use them both together, I'm always open to changing things :)

**Comment by nosilver4u** [comment]
@galbaras Moving this to our new feedback platform, want to see if we can generate more traction that way and get folks involved: https://feedback.ewww.io/b/features/p/enabling-webp-background-images-when-using-picture-tags-with-js-webp-lazy-load

**Comment by galbaras** [comment]
According to [this guide](https://css-tricks.com/using-webp-images/), this can be accomplished by a small script that tests the browser's WebP capability and adds a class to the BODY tag. But I don't see this happening on my pages, although I'm pretty sure the check is being performed.

Seems like a small thing to add. Can you please add this?

Obviously, developers will need to handle the CSS side of things, but at least it will then take effect.

**Comment by nosilver4u** [comment]
At this point, we already cover everything except external CSS, but I think that's probably where you are going with this.
While it's a small thing to add, it also seems like a very small % of users who benefit, no? Do you have an example case where this would be beneficial already?

**Comment by galbaras** [comment]
By "external CSS", you mean a stylesheet, as opposed to an inline STYLE block? If that's the case, I'd say that most sites use several "external" stylesheets and would benefit from such processing, as long as it's not too slow.

Rather than using JavaScript to swap the background images, why not set a BODY class, e.g. "webp", and let developers code their styles to suit? It's easy and flexible, and the downside, if any, is minimal, assuming the checker script is inline and always appears ahead of the CSS, so there's no double-loading of images (note to page optimizers, like Autoptimize).

To test, I've moved the styles of the two top background images on https://www.ronitbaras.com/ to an inline block in the HEAD, and they are still loaded in JPEG format. This is with v6.0.0, with both Picture and JS WebP turned on.

**Comment by nosilver4u** [comment]
Yes, it would affect both separate files and inline style blocks, as neither is currently covered by the WebP rewriters.
We already handle those with our Easy IO service, so there's one potential solution :)

While I'm doubtful we'll get much buy-in from page builders (given past experience trying to work with them), you're welcome to post the idea over at https://feedback.ewww.io and see how much interest we can drum up.

**Comment by galbaras** [comment]
So first, you say:

> At this point, we already cover everything except external CSS

Then, you say:

> neither is currently covered by the WebP rewriters

Is there some way, using the current version, to serve WebP images to capable browsers?

My sites aren't built with page builders. Why is this relevant?

The premise here is that the JS method is being used already. We don't need anything else when using .htaccess rules. Can you please look into this?

**Comment by nosilver4u** [comment]
Sorry, I shortened that bit about the page builders and lost some context! Let me back up a bit and clarify...

We have 4 ways to deliver WebP: .htaccess, JS WebP, picture WebP, and Easy IO.

Easy IO is currently capable of delivering every image via WebP, even ones in external CSS: both style blocks, and separate .css files.
Of course .htaccess would handle WebP for all images, background & standard img elements as well.
picture WebP, by itself, does only img elements.
In 6.0, I added the ability for picture WebP & JS WebP to be enabled at the same time, for the purpose of handling CSS background images. This requires our lazy loader as well, but then JS WebP gains the ability to do CSS background images if they are directly attached to an element via the style attribute (div, span, li, section, and a tags).

Thus the only "gap" in what we support with JS WebP is "external" CSS, and one of the most common places we see background images in "external" CSS is with page builders, though I figured you might not be using one.

So here's my main point: if you have control of the CSS, there's a good chance you can control the HTML markup as well, and can put the background images right in a style attribute, where JS WebP + Lazy Load can take care of them. If another plugin or theme wants to get on board, they can do the same thing (use style attributes instead of external CSS), and no more code is necessary on our end.

Thus, the only target audience for a "body class" is folks who have control over said external CSS, but cannot modify the HTML markup to use style attributes.
That's not to say I think it's a horrible idea, I think it might be useful, but I don't know how many people it would actually help. So that's why I suggested posting it on the feedback site to see if there are any other folks interested. That is, of course, if you actually still need it. Because from what you said earlier, you might have had your background images in style attributes originally, and all this is a moot point.

**Comment by galbaras** [comment]
https://feedback.ewww.io/features/add-webp-class-to-body-on-capable-browsers-to-allow-optimized-background-image-styling-js-webp
