### ISSUE TITLE
SVG optimization support

### ISSUE THREAD

**Issue by samsk** [nosilver4u/ewww-image-optimizer#191]
Hi,
  I would like to have optimization/cleanup support for SVG files in ewww-image-optimizer. The question is, if there is interest for such a feature, and if I implement it, if my change would be accepted to the upstream ?

The optimization itself should be provided by [svgcleaner](https://github.com/RazrFalcon/svgcleaner) binary.

**Reasons to do SVG cleanup**
SVG files created by image editors, have often lot of unnecessary meta tags, are indented and contain other unnecessary ballasts. These ballasts can sometime take up to 80% of the original file, in the case of very simple SVGs, and removing them will decrease file size without affecting the mage itself.

Thank you

**Comment by nosilver4u** [comment]
I'll have to give that some more thought, but my initial reaction is no, it would not be included into the core EWWW IO plugin, at least not as a free feature.
Now, way back, there was talk of trying to use svgo, but the myriad of options, plus the fact that I rarely make my own SVGs, and it seemed SVGO had a reputation for breaking things made me take a hard pass on that (after giving it a LOT of thought).

svgcleaner seems a bit more promising at first glance. It looks like they have worked to resolve some of the problems from SVGO without a lot of fuss and hassle.
We run into a couple problems though:
1. svgcleaner is still known to break SVG files. The free version of EWWW IO doesn't keep backups, I don't like breaking files, and folks like to freak out if something breaks.
2. It's huge, at least at first glance. Perhaps a CLI-only binary would be smaller, but 9MB binaries would be impossible to bundle with the plugin, even more so with three different platforms. So an installation routine would be necessary for folks to auto-install the correct binary for their web server (we do have code that does a similar process with PNGOUT, so that helps).

All that said, I need to think on it a bit longer. I think it might be feasible, but it makes me a bit nervous. It would be better to implement something like this via the API, where we can store backups for the SVGs just in case something goes sideways. But again, I'll give it some more thought.

**Comment by samsk** [comment]
- svgcleaner CLI binary has only ~2MB.
- You are right, there are some issues with svgcleaner breaking files. SVG cleanup functionality could be disabled by default, so only people who are aware of the risk enable it - what do you think ?

**Comment by nosilver4u** [comment]
That helps, but I think it would still need to be downloaded, but I couldn't find any place where the author provides CLI binaries (my archive extractor was throwing fits on the downloads they have).
Realistically, I'd have to build them myself and host them (for security purposes), unless you know of a good "authoritative" source that has CLI binaries for Linux, Windows, and Mac OS.
For dev purposes, we at least need to know that it's possible to build CLI-only binaries for the 3 platforms, and have good instructions for doing so. If you want to build them yourself at this stage, I can put them on the API servers for hosting, and then I'll have to replace those with my own builds before releasing the code in an official release.

And yes, it would definitely be disabled by default. I could envision it below the PDF compression level setting, where it would start out as "SVG Optimization: Disabled/Enabled" -- The Enabled option would be grayed-out/disabled until they use the one-click link that auto-installs the binaries for them.

I'm still working pretty heavily on something else, so please give me one more day to make a final determination on this. I'll give you a definitive answer tomorrow (Wednesday). Feel free to bother me if I forget and you don't see anything by Thursday :)

**Comment by samsk** [comment]
The binaries can be download here - https://github.com/RazrFalcon/svgcleaner/releases/tag/v0.9.5 - I've tried the linux one, and it works. I can create a docker-compose solution for building the binaries.

Ok, I wait for you answer ;-)

**Comment by nosilver4u** [comment]
Ah, those binaries would work quite nicely (with an auto-installer like the pngout one)! I wouldn't mess with anything further on the binaries then, and for the platforms that don't have pre-built binaries (Solaris, BSD, etc.), folks can just use the API.

So I think the main pieces you'll need would be a section in the core ewww_image_optimizer() function that is similar to the one for GIFs, except with no conversion options: 
https://github.com/nosilver4u/ewww-image-optimizer/blob/master/unique.php#L2462

And then the auto-installer here: https://github.com/nosilver4u/ewww-image-optimizer/blob/master/unique.php#L2782

And the UI bits for the settings page right around here: https://github.com/nosilver4u/ewww-image-optimizer/blob/master/common.php#L10369

Looking forward to seeing what you come up with, let me know if you need any feedback along the way. Also, it helps if you can validate your code via the WP coding standards, though our Travis CI integration will check any pull requests automatically.

**Comment by nosilver4u** [comment]
We're halfway there... Well, probably more than halfway, thanks @samsk!
Just need to work on the cloud-based version now, will post updates here as I go along.

**Comment by nosilver4u** [comment]
Alright, cloud-based opt is up and running, just need to double-check the Mac & Windows installation.

**Comment by nosilver4u** [comment]
Well, looks like the .zip files need a different extraction routine, so need to work that out now.

**Comment by nosilver4u** [comment]
Installer now works on Mac & Windows both, looks good!

**Comment by samsk** [comment]
Thank you
