### ISSUE TITLE
WebP files are only generated once and not updated

### ISSUE THREAD

**Issue by oasit** [nosilver4u/ewww-image-optimizer#196]
We are setting a focus point in the media library to our images. The focus point changes the crop area of the image. After changing/setting the focus point the image is generated again. This works for JPEG images (no matter EWWIO is enabled or not) but not for WebP images.
It seems that once created, WebP files are never touched again by EWWWIO.

We also noticed, that when deleting a WebP file from disk, it is never generated again, even not with bulk optimization or "Force Regenerate Thumbnails" (by Pedro Elsner).

It would be nice if EWWWIO could look at the file mod time of the corresponding JPEG file (thumbnail) and if a WebP file already exists before deciding to regenerate a new WebP file or not.

**Comment by nosilver4u** [comment]
If EWWW IO doesn't compress an image, it won't (re)create a WebP version of that image. But if an image is altered, and EWWW IO is called to re-compress the image, it should be re-creating the WebP image. A bulk optimize should also do the same after an image is changed. The only thing that prevents EWWW IO from re-optimizing an image is if the filesize has not changed.

In your other case, if you delete a WebP file, and the JPG/PNG is not altered, then that is correct: the WebP will not be re-created. The Force Regenerate Thumbnails plugin should take care of that (in theory), but I don't know how reliable that plugin is anymore--I've tried to contact the author and gotten no response. And certainly the thumbnail regen wouldn't do anything for the full-size original, only for thumbs and other resized versions.

We don't use file mod times, because those can change when permissions are updated, whereas the file size will change anytime the image changes (except in some weird freak circumstance, but that's never happened in 8+ years).

**Comment by oasit** [comment]
Recreating the JPEG files is working fine and EWWWIO compresses all those regenerated JPEG files (I've verified this in the database: wp_ewwwio_images) no matter if WebP generation is activated or not.
But WebP files are never generated again (even if they are missing; have been delete before manually).

**Comment by nosilver4u** [comment]
Do they get regenerated if you run the bulk optimizer in force re-optimize mode with WebP only checked?

**Comment by oasit** [comment]
Yes. With force re-optimize and WebP only checked, they are regenerated again.

**Comment by nosilver4u** [comment]
Well, that's as expected...
If you can give me exact steps to reproduce something that contradicts what I said above (WebP files always get recreated if 1. the filesize changes and 2. EWWW IO re-optimizes the image), that would be most helpful.
At this point, I'm not quite clear on how you managed to get EWWW IO to re-optimize images without re-creating their WebP variants originally.
