### ISSUE TITLE
s3 Uploads - Thumbnail generation fails

### ISSUE THREAD

**Issue by robin-scott** [nosilver4u/ewww-image-optimizer#22]
Thumbnail generation fails with Ewww enabled, and the plugin [s3 uploads](https://github.com/humanmade/S3-Uploads) (the Human Made version) active.

Workaround for now is to optimize using WP CLI / Cron task and use define `define( 'EWWW_IMAGE_OPTIMIZER_NOAUTO', true );` to prevent optimization on upload, which allows all image sizes to generate, and all images to offload to s3 as expected.

Have not identified root cause here.

Note WP CLI and cron both work just fine to optimize once images have been generated.

**Comment by nosilver4u** [comment]
What version of the S3 Uploads plugin are you using?

**Comment by robin-scott** [comment]
Version 2.0.0

**Comment by nosilver4u** [comment]
Alright, the culprit was in a reworking of the WP_Image_Editor extensions. The plugin normally "disables" these during thumbnail generation, because it's better to wait until for optimization just a bit later in the process. It does so by simply calling the parent function, and returning the result.

But with the extension for S3 Uploads, that approach causes the image to be missing from S3 altogether. So I moved the "preempt" such that it only prevents premature optimization, but allows the S3 upload to occur as it normally would.

Fix has been committed to master if you'd like to grab it and try it out.

**Comment by robin-scott** [comment]
Yes - will have this looked into next maintenance window. It would be a slightly better process for the amount of images uploaded if these were optimized sooner than cron after upload. I'll post up here only if there's any issues popping up, though your description sounds exactly like it will have picked this up. Thanks for looking at it.
