### ISSUE TITLE
EWWW Image Optimizer destroys animated PNG files (lost $$$)

### ISSUE THREAD

**Issue by mdrejhon** [nosilver4u/ewww-image-optimizer#220]
**Describe the bug**
My website uses animated PNGs on some pages at [blurbusters.com/stroboscopics](https://blurbusters.com/stroboscopics) and [blurbusters.com/faq/lcd-overdrive-artifacts](https://blurbusters.com/faq/lcd-overdrive-artifacts).

EWWW Image Optimizer destroyed the animated PNG files.

I wasted time and money fixing the damage EWWW Image Optimizer (which is why I am about to post a bad review, unless this is fixed).  It took me 10 hours to restore from my backups because my backups were hard to access.   I solved the problem by renaming animated PNGs to *.apng (not an officially supported Wordpress extension without a file-renamer plugin), and adding an exclusion to EWWW Optimizer for *.apng so the animated PNG files are no longer optiimized.

There are many PNG optimization utilities such as optipng which automatically skips animated PNGs to avoid destroying them.  Can EWWW Image Optimizer automatically skip animated PNGs?

**OPTION A: To Reproduce (Ongoing damage)**
1. Upload an animated PNG file to your Wordpress page
2. Run EWWW Image Optimizer
3. The original file no longer is animated.

**OPTION B: To Reproduce (Retroactive damage)**
1. Run EWWW Image Optimizer on an old Wordpress server
2. EWWW Image Optimizer destroys 5 years worth of existing animated PNG files **without notifying which files got downgraded to non-animated**

**Expected behavior**
EWWW Image Optimizer should not destroy animated image files

**Sample Images**
For example animated PNGs to test on your EWWW Wordpress server, save the animated PNGs from either [blurbusters.com/stroboscopics](https://blurbusters.com/stroboscopics) or [blurbusters.com/faq/lcd-overdrive-artifacts](https://blurbusters.com/faq/lcd-overdrive-artifacts), then rename .apng back to their original .png they used to be. Then upload to your server to see the animations stop if EWWW is enabled.

Good sample image:
https://blurbusters.com/wp-content/uploads/2018/12/Acer_XB252Q_Animated.apng
(Don't forget to rename back to .png as .apng is a nonstandard extension)

**Additional context**
EWWW Image Optimizer supports optipng which automatically skips animated PNGs.  Can't EWWW be modified to poll the file to check whether it's an animated PNG, before running other tools (e.g. pngcrush) that wrecks animated PNGs, unlike optipng, which respects animated PNGs?  

Even other optimzers (CloudFlare) automatically leaves animated PNGs alone.

I wasted over a hundred dollars worth of work time repairing the damage EWWW did, as the damage was not discovered long after the backups were saved to cold storage, and I had to go one-by-one to figure out which used to be an animated PNG (thousands of PNGs, not knowing which ones used to be animated or not).  It wasn't until after some complaints that this damage was retroactively discovered, so restoring from backups was not an easy/fun task.

There was no warning message telling me about risks with animaged PNGs.

*Note: WebP can also be animated too, some optimizers now exist to convert animated PNGs/GIFs to animated WebP, but this is a very rare conversion process not supported by many.  But converters exist (example https://ezgif.com/apng-to-webp ...).  At the minimum, I want animated PNGs to be simply untouched rather than destroyed (animations removed).*

**Comment by mdrejhon** [comment]
# How to Programmatically Detect animated PNG (so they can be skipped)

https://stackoverflow.com/questions/4525152/can-i-programmatically-determine-if-a-png-is-animated

> APNG images are designed to be "camouflaged" as PNG for readers that not support them. That is, if a reader does not support them, it will just assume it is a normal PNG file and display only the first frame. That means that they have the same MIME type as PNG (image/png), they have the same magic number (89  50  4e  47  0d  0a  1a  0a) and generally they're saved with the same extension (although that is not really a good way to check for a file type).
> 
> So, how do you distinguish them? APNG have a "acTL" chunk in them. So, if you search for the string acTL (or, in hex, 61 63 54 4C (the 4 bytes before the chunk marker (i.e. 00 00 00 08) are the size of the chunk in big endian format, without counting the size, marker, or CRC32 at the end of the field)) you should be pretty good. To get it even better, check that this chunk appears before the first occurrence of the "IDAT" chunk (just look for IDAT).
> 

This code (taken from http://foone.org/apng/identify_apng.php ) will do the trick:

```
<?php
# Identifies APNGs
# Written by Coda, functionified by Foone/Popcorn Mariachi#!9i78bPeIxI
# This code is in the public domain
# identify_apng returns:
# true if the file is an APNG
# false if it is any other sort of file (it is not checked for PNG validity)
# takes on argument, a filename.
function identify_apng($filename)
    {
    $img_bytes = file_get_contents($filename);
    if ($img_bytes)
        {
        if(strpos(substr($img_bytes, 0, strpos($img_bytes, 'IDAT')), 
                 'acTL')!==false)
            {
        return true;
        }
        }
    return false;
    }
?>
```

**Comment by nosilver4u** [comment]
Hi @mdrejhon! I'm sorry you had to find out about that the hard way, doesn't sound like a fun experience at all.
I've only just become aware in the past few days that EWWW IO is not always preserving APNG files, but I thought it was actually optipng that was the culprit. I've just tested with your image and one other that I had available, and optipng does indeed skip those images with this verbage:
Can't reliably reduce APNG file; disabling reductions.

So now I'm puzzled, because optipng is all that the free version uses, unless you had installed PNGOUT, and (offhand) I don't know what that might do to an APNG file.
BUT, I've tested via our API, and that does appear to be removing animation, so I'll have to see what tool it is that is doing this and fix the problem.

Do you know if it was perhaps via the API that your images were processed?

**Comment by mdrejhon** [comment]
The web server has pngout, pngcrush and optipng installed.  

It was last month so I don't know which tool EWWW uses by default, but I haven't uninstalled any tool.   

The bottom line is that I didn't know what EWWW was going to do with my animated PNGs which was the part that bothered me the most.  

Either way, please **pay it forward** and complain to that third party tool for me, pretty-please-with-sugar-on-top.   We need to decontaminate the Internet of buggy PNG tools...

**Comment by nosilver4u** [comment]
Ah, I think the -strip option is the culprit then. We don't use pngcrush, and only pngout if it's in the wp-content/ewww/ folder.
If you were using the API, you'd already know that, and would have an API key entered in the settings (very top of the Basic tab).
Metadata removal is enabled by default, which triggers "-strip all"

The -strip option makes sense, because I was puzzled when you referenced the Optipng changelog claiming to be "APNG-safe", as my experience from last week indicated otherwise. I was doing some comparison tests then between optipng and oxipng, and having just become aware of some potential issues with APNG files, I noticed optipng was stripping animations, and oxipng was not. And now that you mentioned the -strip option, I know for a fact I was stripping metadata in my tests. Apparently, -strip also removes animations, but that's not readily obvious from the documentation: "PNG metadata is the information stored in any ancillary chunk except tRNS."
--maybe you knew what that meant,  but that's not helpful to me at all

The important thing now, is to stop EWWW IO from doing this. While it would help to have animations listed in the description for Remove Metadata, too many folks don't read things, and so I'd rather prevent that option from ever being applied to APNG files if we can.
The code you provided is a good starting point, so I'll see what we need to do to make EWWW IO APNG-safe.

**Comment by mdrejhon** [comment]
It seems pretty clear about the **-snip** but very unclear about the **-strip** option:

![image](https://user-images.githubusercontent.com/59981975/112381992-e50e8980-8cb0-11eb-9ea5-6df8d53d0f9b.png)

I think some manual local tests are in order, to figure out if this is /really/ the culprit.  There's a lot of potential ways to clobber an apng by accident that are overlooked.

**Comment by nosilver4u** [comment]
Indeed, the -snip option is much clearer on that point :)
I've been doing manual tests on all the tools we use, and here are my findings:
optipng: removes animations with -strip all
pngout: removes animations by default unless you choose to keep optional chunks with -k1.
pngquant: does not keep animations nor have a way to preserve metadata (author is already aware of APNG)

If you had Remove Metadata unchecked, then it's possible pngout was the culprit here, as EWWW IO was not making use of the -k1 flag to preserve said metadata with pngout.

I've already implemented fixes for local/free optimization to ensure APNG animations are preserved regardless of the Remove Metadata option, so those will be in the next release.

**Comment by nosilver4u** [comment]
This is now fixed on the API and Easy IO as well.

**Comment by mdrejhon** [comment]
Excellent!  Look forward to the plugin update.
