### ISSUE TITLE
Lazy load image size problem

### ISSUE THREAD

**Issue by consultingroupitaly** [nosilver4u/ewww-image-optimizer#232]
**Describe the bug**
The size of the logo is wrong with lazy load.

**To Reproduce**
1. Enable lazy load
2. Logo is messed up

**Screenshots**
Here with lazy load enabled for all images:
![with-lazyload](https://user-images.githubusercontent.com/44967141/122405549-6f008280-cf80-11eb-91ef-b0c37f23b3cd.png)
Here with the logo excluded from lazy load:
![without-lazyload](https://user-images.githubusercontent.com/44967141/122405624-7de73500-cf80-11eb-9af7-f531583a3ca5.png)

**Comment by nosilver4u** [comment]
I can't see any inherent problems from the page source, so I'd have to see it in action. Please provide a screenshot of the HTML page source code for the logo (you can also right click on it, and choose Inspect to jump right to the logo element).

**Comment by consultingroupitaly** [comment]
I'm leaving the page with lazy load enabled for 1 day so you can see directly here: https://www.consultingroupitaly.com/

**Comment by nosilver4u** [comment]
That's perfect, now I can see there is an issue with filling in the width/height attributes, which is what I suspected.

The logo image is 250 x 250 px, so that's what is filled in. The problem then, is that your CSS says the logo should be 100px tall, but has no width boundary. The CSS for img elements says to use max-width: 100%. Thus the image is set to 100px tall, and 100% width, which gives you a 100 x 250 box in which to put a 250 x 250 image.

![Screenshot from 2021-06-17 09-31-42](https://user-images.githubusercontent.com/6015678/122428357-11077700-cf4f-11eb-8282-b7e863e97952.png)

You can either make your logo the "right" size (100 x 100 px), or add a CSS rule to make max-width = 100px for ".mob-standard-logo".
Note that your "retina" logo has the same issue, but with different dimensions, since it's a 500px square (rather than 200px).

Or, of course, you can just keep it excluded, since there is zero benefit from lazy loading your logo, which is right at the top of the page, and cannot be auto-scaled (and doesn't really need to be, since it's tiny).

**Comment by consultingroupitaly** [comment]
Thanks.
So the issue is probably with the Mobile Menu plug-in.
Simply setting `.mob-standard-logo {width:auto}` seems to fix it.

I still prefer lazy loading because it make the page loading go ahead while the image is loading and also because it fix "missing width and height attributes to images" in pagespeed without modifying code directly.

**Comment by nosilver4u** [comment]
Make sure to set the same for .mob-retina-logo too, or folks on hi-dpi devices (like iPhones and Macs) will get the same squished logo :)

**Comment by consultingroupitaly** [comment]
Yes, thanks.
