### ISSUE TITLE
WepB support of WordPress 5.8

### ISSUE THREAD

**Issue by consultingroupitaly** [nosilver4u/ewww-image-optimizer#237]
Hi,
this is mainly a question.

Is this plug-in already compatible with the integrated WepB support of WordPress 5.8 or not yet?

Best regards.

**Comment by nosilver4u** [comment]
I've not specifically tested a WebP upload yet, though I hope to do so before the 5.8 release. In theory, it all should "just work" because EWWW IO won't do anything with a WebP image upload. Short of just re-compressing such images "blindly" at a lower quality, there's not much for EWWW IO to do with them anyway. So the main thing will be just ensuring EWWW IO ignores WebP uploads (for now).

**Comment by consultingroupitaly** [comment]
Thanks for the info.
