### ISSUE TITLE
6.2: amp_is_available was called incorrectly. WordPress  is currently doing the `eio_do_lazyload` hook.

### ISSUE THREAD

**Issue by lkraav** [nosilver4u/ewww-image-optimizer#245]
**Describe the bug**
We're mistiming `amp_xyz()` calls.

**To Reproduce**
Install https://wordpress.org/plugins/amp/

**Expected behavior**
Avoid calling `is_amp()` too early.

**Additional context**
Traceback: https://sentry.io/share/issue/f9dd91e64cef479d8098d28ac92a0ac7/

This is massive log spam: thousands of events / day.

To avoid warning event flood, I monkey-patched like below

```php
                        if ( false !== strpos( $uri, '/amp/' ) ) {
                                return false;
                        }
```

**Comment by nosilver4u** [comment]
Thanks for reporting that! Go ahead and grab the latest code here on GitHub and see if that works well for you.

**Comment by lkraav** [comment]
I just updated to 6.2.4 release, and it appears https://github.com/nosilver4u/ewww-image-optimizer/commit/9b55d415f4f6b8d2df2e614bb0d02743841e8984 doesn't do anything to fix this issue :(

Fresh traceback https://sentry.io/share/issue/f9dd91e64cef479d8098d28ac92a0ac7/

I will re-monkey-patch with `strpos()` while investigation continues.

**Comment by nosilver4u** [comment]
Hmm, that's odd, I wonder if our check isn't strict enough? I'll dig into this further and see what is going on there.

**Comment by nosilver4u** [comment]
Odd indeed, all the core "conditional tags" use the same check that we do, but that doesn't really seem to work correctly.
I even tried checking to see if $wp_query was a WP_Query object, and that didn't help. Only when I checked to see if the 'parse_query' action had been run was I able to get the proper safety check.
So that's what we'll roll with (in addition to the existing checks). Updated code has been committed to master.
