### ISSUE TITLE
Slow SQL date updates

### ISSUE THREAD

**Issue by cbratschi** [nosilver4u/ewww-image-optimizer#276]
**Describe the bug**

**To Reproduce**
1. Open the posts screen in WordPress
2. Look for slow queries in debug bar.

Seeing this query takes about 1.5 s:

```sql
UPDATE wp_ewwwio_images
SET updated = '1971-01-01 00:00:00'
WHERE updated < '1001-01-01 00:00:01'
```
The database table contains 1.2 million items.

**Expected behavior**
This slow SQL should not be executed every time.

**Screenshots**

**Debugging Information (please enable the debugging information from the plugin settings, redact as necessary):**

**Sample Images**

**Additional context**
Code location:

https://github.com/nosilver4u/ewww-image-optimizer/blob/ca55bee3cdedba064ac5d1d780f9fd9d8310d8b9/common.php#L1607

**Comment by nosilver4u** [comment]
Thanks for reporting that, I'm thinking we could potentially improve things by checking to see if an update is at all necessary on the updated column.
This query only runs once per upgrade though, so it certainly shouldn't be executing every time you open the posts screen. If you're seeing it run every time, clear any database/object cache. If the issue persists, then check to make sure the ewww_image_optimizer_version is set correctly in the wp_options table (should be 641.0).

Would you please run the following query to see if it would improve things--MySQL will usually report the query time, so that's the value we'd be interested in:

`SELECT * FROM wp_ewwwio_images WHERE updated < '1001-01-01 00:00:01' LIMIT 1`

Of course, if you're using a custom table prefix, change the table name before you execute the query.

**Comment by cbratschi** [comment]
Hi @nosilver4u,

This code is running every time on our servers. This happens both on our staging and prod environments which use different Memcached instances and databases.

Debug cache shows this stack trace:

- ewww_image_optimizer_install_table
- ewww_image_optimizer_upgrade
- ewww_image_optimizer_admin_init
- WP_Hook->apply_filters
- WP_Hook->do_action
- do_action('admin_init')
- require_once('wp-admin/admin.php')

I did not check the source code yet for more details. Will do this next.

ewww_image_optimizer_version has the value "641.0".

The follow query took 1.8 seconds:

```sql
SELECT * FROM wp_ewwwio_images WHERE updated < '1001-01-01 00:00:01' LIMIT 1
```

We have no invalid dates in our table, so this query always performs a full table scan because there is no index for updated.

**Comment by cbratschi** [comment]
Well, "640.0" was in the Object Cache. "641.0" was in the database. So this was a caching issue and this SQL query is fine for upgrade cases.

Thanks for your help.

**Comment by nosilver4u** [comment]
Thanks for checking through all that, I suspected it was a stale version in the cache, so I'm glad that cleared it up!
