### ISSUE TITLE
Add AVIF conversion, the same as webp 

### ISSUE THREAD

**Issue by fidoboy** [nosilver4u/ewww-image-optimizer#305]
Please, take a look at this: https://github.com/kornelski/cavif-rs and add the executable, the same as it's doing right now cwebp from command line exec

**Comment by nosilver4u** [comment]
Feature requests belong on our feedback site, but regardless the answer is no. See also: https://feedback.ewww.io/p/local-avif-support

**Comment by fidoboy** [comment]
Ok. What it says the link is not true. But I've modified ewww-image-optimizer to work with cavif anyway. It's just a small change.

regards,

**Comment by nosilver4u** [comment]
This issue is closed because it will not be implemented in EWWW IO. The CPU demands of AVIF conversion are too high, and I can't in good conscience unleash that on over a million sites.

**Comment by fidoboy** [comment]
Well, I've understand your answer the first time. That's why the issue is not closed. If you do not want to implement it, I understand it. But the issue is not closed then. It's my thread, not yours.

**Comment by fidoboy** [comment]
> This issue is closed because it will not be implemented in EWWW IO. The CPU demands of AVIF conversion are too high, and I can't in good conscience unleash that on over a million sites.

If it is "too high" Why your CDN supplies the AVIF format? Do you have a computer that doesn't depend on high CPU demands?

All computations depends on CPU demands anyway :D

**Comment by nosilver4u** [comment]
We provide AVIF on the CDN because our servers are dedicated to compressing images. That's their job. Your web server's job is to deliver web pages, not to compress images. Even still, we had to put some pretty tight limits on AVIF, and we implemented AVIF knowing that it would increase our server costs (and it has).

Certainly, many web hosts allow EWWW IO to operate (in local mode) because the overhead of local compression is not sufficient enough to blow up a server (usually). But, there are some web hosts that strictly prohibit local/exec mode because of the CPU overhead already. And we've even seen cases where web hosts won't tolerate the database load of a bulk optimization, let alone doing local compression.

Now, you may be in a situation where you don't care, perhaps you run your own server (VPS or dedicated), and have plenty of "head space" to run cavif-rs on your images.
But most of our users are on shared hosting, and I can't in good conscience unleash AVIF encoding on all those servers. We risk EWWW IO getting banned, users getting their service suspended, and a whole host of negative feedback from EWWW IO overloading servers, and that's not a risk I'm willing to take.

**Comment by fidoboy** [comment]
As I've said, I understand you. I also have a server dedicated to compress images, that's why I use the ewww plugin, because it works locally and uses my own server.

This is a decision that is up to the plugin user to make. In many cases, it is normal that they prefer to delegate this work to other servers, at the cost of violating their own security.

**Comment by fidoboy** [comment]
That said, I agree with you about the issue in shared hostings. But that's not my problem, or yours or what this plugin could be involved in a solution.

**Comment by fidoboy** [comment]
In the same way, this could also apply to almost any WordPress plugin, since those that are used to make backups, running libzip for example, have the same problem. Or in any other process that demands a bit of CPU for some time, causing high spikes in usage. But even in the case of small servers, it is always better to spread that load among many, than on a single one whose activity thousands and thousands of sites can depend. It all depends on the wisdom of each site administrator to put in a queue of processes without blowing up the server. There are hours of low workload where it can be done without probememation. And users of small sites, in shared hosting, also tend to have a very small number of images, so this operation is usually of the "once in a lifetime" type.
