### ISSUE TITLE
srcset not being capped at manually set resolution

### ISSUE THREAD

**Issue by cap-mfm** [nosilver4u/ewww-image-optimizer#335]
**Describe the bug**
I have a list of posts I show on my website's home page, for which I want the featured image to be displayed at a certain size (the size slug is `medium`, which has a max width of 500px). I still need the larger versions of the featured images for obvious reasons (they'll eventually get rendered at full size on the single post pages). I've picked the resolution (`medium`) I want inside of my page editor, but the images are always getting served at full size, because the `srcset` getting generated by EWWW goes all the way up to their full-sized version.

##### Example:
```html
<img width="500" 
  height="283" 
  src="https://mysite.example/wp-content/images/test-image-1-500x283.jpg" 
  class="attachment-medium size-medium wp-post-image"
  decoding="async"
  loading="lazy"
  srcset="https://mysite.example/wp-content/images/test-image-1-500x283.jpg 500w, 
    https://mysite.example/wp-content/images/test-image-1-768x435.jpg 768w,
    https://mysite.example/wp-content/images/test-image-1.jpg 1000w"  
  sizes="(max-width: 500px) 100vw, 500px"
/>
```

In this example you can see the `src` attribute is correctly referencing the `medium` resolution variant of the image, but users are getting the full size version rendered anyway because of the srcset that gets injected into the `img` tag.

Is there any way to *not* generate that `srcset` for specific cases, like this one, where I want a handpicked resolution variant to exclusively get rendered?

**Comment by nosilver4u** [comment]
Nothing about that img element looks like EWWW IO is involved. That looks like a completely stock WP image element, and those do often have issues with incorrect sizes being served. That's why our lazy loader has an auto-size mechanism, so that the lazy loader can set the image to display that matches the exact size of the element. I think there are ways to programmatically suppress srcset insertion from WP core, but I don't know of any plugin that does such a thing.

That said, if you can share an example, I can double-check why it is using a larger version of the image. I do know that you might get a larger image requested on retina screens (most modern phones) because they want 2-3x the pixels, so 500px is no longer enough.
