### ISSUE TITLE
Image size not found

### ISSUE THREAD

**Issue by valentin-anamorphik** [nosilver4u/ewww-image-optimizer#347]
**Describe the bug**
- Image size not found

**To Reproduce**
1. Regenerate picture : `wp media regenerate`
2. In database,` _wp_attachment_metadata` (files entry) is empty.

**Notes**
Think it's the images that have the suffix '-rotated' and '-scaled'.

I disabled EWWW's auto-resizing and auto-rotation (`define( 'EWWW_IMAGE_OPTIMIZER_DISABLE_AUTOROTATE', true );`).

**Comment by nosilver4u** [comment]
Could you please clarify the actual issue you are seeing? Is it just missing metadata, or are the thumbnails actually missing?
Are you seeing an actual "Image size not found" error anywhere?

EWWW IO has no (known) issues with -rotated and -scaled images, we deal with those all the time. To narrow this down, first disable EWWW IO and make sure the issue is gone. If so, then please disable all plugins except EWWW IO, revert your potential fix, and see if the issue persists.

Lastly, please post the system information from the EWWW IO settings, and the site info from the Site Health section.

**Comment by valentin-anamorphik** [comment]
Hi @nosilver4u ,

The images are successfully generated, optimized, and present on the server.
After running the wp media regenerate command, the metadata is present in the database.
![Capture d'écran 2024-12-12 090635](https://github.com/user-attachments/assets/0becd2e4-7416-4f43-8944-3a10a58fbf23)

However, after displaying the image on the website frontend, the metadata is missing (deleted) from the database.
![Capture d'écran 2024-12-12 090740](https://github.com/user-attachments/assets/e1903fcc-631e-45f3-9bcb-45446ba99a71)

When visiting the site, the image does not appear as missing (404), but the displayed image is the original (original size).

We performed the same operation with the EWWW IO plugin deactivated. In this case, when viewing the page containing the image, the metadata is not deleted.

However, after reactivating the EWWW IO plugin, we revisited the page containing the image, and this time, the metadata is not deleted.

Regarding report submission, is it possible to use another support channel instead of GitHub?

Thank you for your assistance.

**Comment by nosilver4u** [comment]
Please send us an email via https://ewww.io/contact-us/ with the additional information and we'll go from there.

**Comment by valentin-anamorphik** [comment]
It's send

**Comment by nosilver4u** [comment]
Per our email conversation, this appears to be a bug in WooCommerce, triggered by disabling all the Woo image sizes within EWWW IO's settings.
