### ISSUE TITLE
Use with S3 Uploads plugin

### ISSUE THREAD

**Issue by Tailzip** [nosilver4u/ewww-image-optimizer#6]
Hi,

Any idea how to make the plugin works with S3 Uploads plugin (https://github.com/humanmade/S3-Uploads)? Right now, when uploading a file, it isn't being optimized. I'm not getting any error ouput though.

Thanks!

**Comment by nosilver4u** [comment]
It's feasible, but because the S3 Uploads plugin is handling images so early, it wouldn't be possible to use background optimization. In other words, it will slow down the upload process a little. We have a plugin that can optimize your S3 buckets also if that helps in the meantime: https://ewww.io/downloads/s3-image-optimizer/

**Comment by nosilver4u** [comment]
Finally took the time to dig into this, took a bit more work than expected, but it turned out better than I expected. All features work properly, even background optimization. The latest commit has all the changes, and 3.5 will be released next week.
